const countries = {
  'Абхазия': 'http://world-weather.ru/pogoda/abkhazia/',
  'Австралия': 'http://world-weather.ru/pogoda/australia/',
  'Австрия': 'http://world-weather.ru/pogoda/austria/',
  'Азербайджан': 'http://world-weather.ru/pogoda/azerbaijan/',
  'Албания': 'http://world-weather.ru/pogoda/albania/',
  'Алжир': 'http://world-weather.ru/pogoda/algeria/',
  'Американские Виргинские острова':
      'http://world-weather.ru/pogoda/us_virgin_islands/',
  'Ангилья': 'http://world-weather.ru/pogoda/anguilla/',
  'Ангола': 'http://world-weather.ru/pogoda/angola/',
  'Андорра': 'http://world-weather.ru/pogoda/andorra/',
  'Антигуа и Барбуда': 'http://world-weather.ru/pogoda/antigua_and_barbuda/',
  'Аргентина': 'http://world-weather.ru/pogoda/argentina/',
  'Армения': 'http://world-weather.ru/pogoda/armenia/',
  'Аруба': 'http://world-weather.ru/pogoda/aruba/',
  'Афганистан': 'http://world-weather.ru/pogoda/afghanistan/',
  'Багамские Острова': 'http://world-weather.ru/pogoda/bahamas/',
  'Бангладеш': 'http://world-weather.ru/pogoda/bangladesh/',
  'Барбадос': 'http://world-weather.ru/pogoda/barbados/',
  'Бахрейн': 'http://world-weather.ru/pogoda/bahrain/',
  'Беларусь': 'http://world-weather.ru/pogoda/belarus/',
  'Белиз': 'http://world-weather.ru/pogoda/belize/',
  'Бельгия': 'http://world-weather.ru/pogoda/belgium/',
  'Бенин': 'http://world-weather.ru/pogoda/benin/',
  'Бермудские Острова': 'http://world-weather.ru/pogoda/bermuda/',
  'Болгария': 'http://world-weather.ru/pogoda/bulgaria/',
  'Боливия': 'http://world-weather.ru/pogoda/bolivia/',
  'Босния и Герцеговина':
      'http://world-weather.ru/pogoda/bosnia_and_herzegovina/',
  'Ботсвана': 'http://world-weather.ru/pogoda/botswana/',
  'Бразилия': 'http://world-weather.ru/pogoda/brazil/',
  'Британские Виргинские о-ва':
      'http://world-weather.ru/pogoda/british_virgin_islands/',
  'Бруней': 'http://world-weather.ru/pogoda/brunei/',
  'Буркина Фасо': 'http://world-weather.ru/pogoda/burkina_faso/',
  'Бурунди': 'http://world-weather.ru/pogoda/burundi/',
  'Бутан': 'http://world-weather.ru/pogoda/bhutan/',
  'Вануату': 'http://world-weather.ru/pogoda/vanuatu/',
  'Ватикан ': 'http://world-weather.ru/pogoda/vatican/',
  'Великобритания': 'http://world-weather.ru/pogoda/united_kingdom/',
  'Венгрия': 'http://world-weather.ru/pogoda/hungary/',
  'Венесуэла': 'http://world-weather.ru/pogoda/venezuela/',
  'Восточный Тимор': 'http://world-weather.ru/pogoda/east_timor/',
  'Вьетнам': 'http://world-weather.ru/pogoda/vietnam/',
  'Габон': 'http://world-weather.ru/pogoda/gabon/',
  'Гаити': 'http://world-weather.ru/pogoda/haiti/',
  'Гайана': 'http://world-weather.ru/pogoda/guyana/',
  'Гамбия': 'http://world-weather.ru/pogoda/gambia/',
  'Гана': 'http://world-weather.ru/pogoda/ghana/',
  'Гваделупа': 'http://world-weather.ru/pogoda/guadeloupe/',
  'Гватемала': 'http://world-weather.ru/pogoda/guatemala/',
  'Гвинея': 'http://world-weather.ru/pogoda/guinea/',
  'Гвинея-Бисау': 'http://world-weather.ru/pogoda/guinea_bissau/',
  'Германия': 'http://world-weather.ru/pogoda/germany/',
  'Гибралтар': 'http://world-weather.ru/pogoda/gibraltar/',
  'Гондурас': 'http://world-weather.ru/pogoda/honduras/',
  'Гренада': 'http://world-weather.ru/pogoda/grenada/',
  'Гренландия': 'http://world-weather.ru/pogoda/greenland/',
  'Греция': 'http://world-weather.ru/pogoda/greece/',
  'Грузия': 'http://world-weather.ru/pogoda/georgia/',
  'Гуам': 'http://world-weather.ru/pogoda/guam/',
  'Дания': 'http://world-weather.ru/pogoda/denmark/',
  'Демократическая Республика Конго': 'http://world-weather.ru/pogoda/congo/',
  'Джерси': 'http://world-weather.ru/pogoda/jersey/',
  'Джибути': 'http://world-weather.ru/pogoda/djibouti/',
  'Доминикана': 'http://world-weather.ru/pogoda/dominicana/',
  'Египет': 'http://world-weather.ru/pogoda/egypt/',
  'Замбия': 'http://world-weather.ru/pogoda/zambia/',
  'Западная Сахара': 'http://world-weather.ru/pogoda/western_sahara/',
  'Зимбабве': 'http://world-weather.ru/pogoda/zimbabwe/',
  'Израиль': 'http://world-weather.ru/pogoda/israel/',
  'Индия': 'http://world-weather.ru/pogoda/india/',
  'Индонезия': 'http://world-weather.ru/pogoda/indonesia/',
  'Иордания': 'http://world-weather.ru/pogoda/jordan/',
  'Ирак': 'http://world-weather.ru/pogoda/iraq/',
  'Иран': 'http://world-weather.ru/pogoda/iran/',
  'Ирландия': 'http://world-weather.ru/pogoda/ireland/',
  'Исландия': 'http://world-weather.ru/pogoda/iceland/',
  'Испания': 'http://world-weather.ru/pogoda/spain/',
  'Италия': 'http://world-weather.ru/pogoda/italy/',
  'Йемен': 'http://world-weather.ru/pogoda/yemen/',
  'Кабо-Верде': 'http://world-weather.ru/pogoda/cape_verde/',
  'Казахстан': 'http://world-weather.ru/pogoda/kazakhstan/',
  'Каймановы Острова': 'http://world-weather.ru/pogoda/cayman_islands/',
  'Камбоджа': 'http://world-weather.ru/pogoda/cambodia/',
  'Камерун': 'http://world-weather.ru/pogoda/cameroon/',
  'Канада': 'http://world-weather.ru/pogoda/canada/',
  'Катар': 'http://world-weather.ru/pogoda/qatar/',
  'Кения': 'http://world-weather.ru/pogoda/kenya/',
  'Кипр': 'http://world-weather.ru/pogoda/cyprus/',
  'Кирибати': 'http://world-weather.ru/pogoda/kiribati/',
  'Китай': 'http://world-weather.ru/pogoda/china/',
  'КНДР': 'http://world-weather.ru/pogoda/north_korea/',
  'Кокосовые острова': 'http://world-weather.ru/pogoda/cocos_islands/',
  'Колумбия': 'http://world-weather.ru/pogoda/colombia/',
  'Коморские острова': 'http://world-weather.ru/pogoda/comoros/',
  'Косово': 'http://world-weather.ru/pogoda/kosovo/',
  'Коста-Рика': 'http://world-weather.ru/pogoda/costa_rica/',
  'Кот-д’Ивуар': 'http://world-weather.ru/pogoda/cote_divoire/',
  'Куба': 'http://world-weather.ru/pogoda/cuba/',
  'Кувейт': 'http://world-weather.ru/pogoda/kuwait/',
  'Кыргызстан': 'http://world-weather.ru/pogoda/kyrgyzstan/',
  'Лаос': 'http://world-weather.ru/pogoda/laos/',
  'Латвия': 'http://world-weather.ru/pogoda/latvia/',
  'Лесото': 'http://world-weather.ru/pogoda/lesotho/',
  'Либерия': 'http://world-weather.ru/pogoda/liberia/',
  'Ливан': 'http://world-weather.ru/pogoda/lebanon/',
  'Ливия': 'http://world-weather.ru/pogoda/libya/',
  'Литва': 'http://world-weather.ru/pogoda/lithuania/',
  'Лихтенштейн': 'http://world-weather.ru/pogoda/liechtenstein/',
  'Люксембург': 'http://world-weather.ru/pogoda/luxembourg/',
  'Маврикий': 'http://world-weather.ru/pogoda/mauritius/',
  'Мавритания': 'http://world-weather.ru/pogoda/mauritania/',
  'Мадагаскар': 'http://world-weather.ru/pogoda/madagascar/',
  'Майотта': 'http://world-weather.ru/pogoda/mayotte/',
  'Макао': 'http://world-weather.ru/pogoda/macau/',
  'Македония': 'http://world-weather.ru/pogoda/macedonia/',
  'Малави': 'http://world-weather.ru/pogoda/malawi/',
  'Малайзия': 'http://world-weather.ru/pogoda/malaysia/',
  'Мали': 'http://world-weather.ru/pogoda/mali/',
  'Мальдивы': 'http://world-weather.ru/pogoda/maldives/',
  'Мальта': 'http://world-weather.ru/pogoda/malta/',
  'Марокко': 'http://world-weather.ru/pogoda/morocco/',
  'Маршалловы Острова': 'http://world-weather.ru/pogoda/marshall_islands/',
  'Мексика': 'http://world-weather.ru/pogoda/mexico/',
  'Микронезия': 'http://world-weather.ru/pogoda/micronesia/',
  'Мозамбик': 'http://world-weather.ru/pogoda/mozambique/',
  'Молдова': 'http://world-weather.ru/pogoda/moldova/',
  'Монако': 'http://world-weather.ru/pogoda/monaco/',
  'Монголия': 'http://world-weather.ru/pogoda/mongolia/',
  'Монтсеррат': 'http://world-weather.ru/pogoda/montserrat/',
  'Мьянма': 'http://world-weather.ru/pogoda/myanmar/',
  'Намибия': 'http://world-weather.ru/pogoda/namibia/',
  'Непал': 'http://world-weather.ru/pogoda/nepal/',
  'Нигер': 'http://world-weather.ru/pogoda/niger/',
  'Нигерия': 'http://world-weather.ru/pogoda/nigeria/',
  'Нидерланды': 'http://world-weather.ru/pogoda/netherlands/',
  'Никарагуа': 'http://world-weather.ru/pogoda/nicaragua/',
  'Ниуэ': 'http://world-weather.ru/pogoda/niue/',
  'Новая Зеландия': 'http://world-weather.ru/pogoda/new_zealand/',
  'Норвегия': 'http://world-weather.ru/pogoda/norway/',
  'О. Гернси': 'http://world-weather.ru/pogoda/guernsey/',
  'ОАЭ': 'http://world-weather.ru/pogoda/uae/',
  'Оман': 'http://world-weather.ru/pogoda/oman/',
  'Остров Мэн': 'http://world-weather.ru/pogoda/isle_of_man/',
  'Остров Рождества': 'http://world-weather.ru/pogoda/christmas_island/',
  'Острова Кука': 'http://world-weather.ru/pogoda/cook_islands/',
  'Острова Теркс И Кайкос':
      'http://world-weather.ru/pogoda/turks_and_caicos_islands/',
  'Пакистан': 'http://world-weather.ru/pogoda/pakistan/',
  'Палау': 'http://world-weather.ru/pogoda/palau/',
  'Палестина': 'http://world-weather.ru/pogoda/palestine/',
  'Панама': 'http://world-weather.ru/pogoda/panama/',
  'Папуа-Новая Гвинея': 'http://world-weather.ru/pogoda/papua_new_guinea/',
  'Парагвай': 'http://world-weather.ru/pogoda/paraguay/',
  'Перу': 'http://world-weather.ru/pogoda/peru/',
  'Польша': 'http://world-weather.ru/pogoda/poland/',
  'Португалия': 'http://world-weather.ru/pogoda/portugal/',
  'Пуэрто-Рико': 'http://world-weather.ru/pogoda/puerto_rico/',
  'Республика Конго': 'http://world-weather.ru/pogoda/republic_of_the_congo/',
  'Россия': 'http://world-weather.ru/pogoda/russia/',
  'Руанда': 'http://world-weather.ru/pogoda/rwanda/',
  'Румыния': 'http://world-weather.ru/pogoda/romania/',
  'Рэюньен': 'http://world-weather.ru/pogoda/reunion/',
  'Сальвадор': 'http://world-weather.ru/pogoda/el_salvador/',
  'Самоа': 'http://world-weather.ru/pogoda/samoa/',
  'Сан-Марино': 'http://world-weather.ru/pogoda/san_marino/',
  'Сан-Томе и Принсипи':
      'http://world-weather.ru/pogoda/sao_tome_and_principe/',
  'Саудовская Аравия': 'http://world-weather.ru/pogoda/saudi_arabia/',
  'Свазиленд': 'http://world-weather.ru/pogoda/swaziland/',
  'Сейшелы': 'http://world-weather.ru/pogoda/seychelles/',
  'Сен-Пьер и Микелон':
      'http://world-weather.ru/pogoda/saint_pierre_and_miquelon/',
  'Сенегал': 'http://world-weather.ru/pogoda/senegal/',
  'Сент-Винсент и Гренадины':
      'http://world-weather.ru/pogoda/saint_vincent_and_the_grenadines/',
  'Сент-Китс и Невис': 'http://world-weather.ru/pogoda/saint_kitts_and_nevis/',
  'Сент-Люсия': 'http://world-weather.ru/pogoda/saint_lucia/',
  'Сербия': 'http://world-weather.ru/pogoda/serbia/',
  'Сингапур': 'http://world-weather.ru/pogoda/singapore/',
  'Сирия': 'http://world-weather.ru/pogoda/syria/',
  'Словакия': 'http://world-weather.ru/pogoda/slovakia/',
  'Словения': 'http://world-weather.ru/pogoda/slovenia/',
  'Соломоновы Острова': 'http://world-weather.ru/pogoda/solomon_islands/',
  'Сомали': 'http://world-weather.ru/pogoda/somalia/',
  'Судан': 'http://world-weather.ru/pogoda/sudan/',
  'Суринам': 'http://world-weather.ru/pogoda/suriname/',
  'США': 'http://world-weather.ru/pogoda/usa/',
  'Сьерра Леоне': 'http://world-weather.ru/pogoda/sierra_leone/',
  'Таджикистан': 'http://world-weather.ru/pogoda/tajikistan/',
  'Тайвань': 'http://world-weather.ru/pogoda/taiwan/',
  'Тайланд': 'http://world-weather.ru/pogoda/thailand/',
  'Танзания': 'http://world-weather.ru/pogoda/tanzania/',
  'Того': 'http://world-weather.ru/pogoda/togo/',
  'Токелау': 'http://world-weather.ru/pogoda/tokelau/',
  'Тонга': 'http://world-weather.ru/pogoda/tonga/',
  'Тринидад и Тобаго': 'http://world-weather.ru/pogoda/trinidad_and_tobago/',
  'Тувалу': 'http://world-weather.ru/pogoda/tuvalu/',
  'Тунис': 'http://world-weather.ru/pogoda/tunisia/',
  'Туркменистан': 'http://world-weather.ru/pogoda/turkmenistan/',
  'Турция': 'http://world-weather.ru/pogoda/turkey/',
  'Уганда': 'http://world-weather.ru/pogoda/uganda/',
  'Узбекистан': 'http://world-weather.ru/pogoda/uzbekistan/',
  'Украина': 'http://world-weather.ru/pogoda/ukraine/',
  'Уругвай': 'http://world-weather.ru/pogoda/uruguay/',
  'Фиджи': 'http://world-weather.ru/pogoda/fiji/',
  'Филиппины': 'http://world-weather.ru/pogoda/philippines/',
  'Финляндия': 'http://world-weather.ru/pogoda/finland/',
  'Фолклендские о-ва': 'http://world-weather.ru/pogoda/falkland_islands/',
  'Франция': 'http://world-weather.ru/pogoda/france/',
  'Французская Полинезия': 'http://world-weather.ru/pogoda/french_polynesia/',
  'Хорватия': 'http://world-weather.ru/pogoda/croatia/',
  'ЦАР': 'http://world-weather.ru/pogoda/central_african_republic/',
  'Чад': 'http://world-weather.ru/pogoda/chad/',
  'Черногория': 'http://world-weather.ru/pogoda/montenegro/',
  'Чехия': 'http://world-weather.ru/pogoda/czech_republic/',
  'Чили': 'http://world-weather.ru/pogoda/chile/',
  'Швейцария': 'http://world-weather.ru/pogoda/switzerland/',
  'Швеция': 'http://world-weather.ru/pogoda/sweden/',
  'Шри Ланка': 'http://world-weather.ru/pogoda/sri_lanka/',
  'Эквадор': 'http://world-weather.ru/pogoda/ecuador/',
  'Экваториальная Гвинея': 'http://world-weather.ru/pogoda/equatorial_guinea/',
  'Эритрея': 'http://world-weather.ru/pogoda/eritrea/',
  'Эстония': 'http://world-weather.ru/pogoda/estonia/',
  'Эфиопия': 'http://world-weather.ru/pogoda/ethiopia/',
  'ЮАР': 'http://world-weather.ru/pogoda/south_africa/',
  'Южная Корея': 'http://world-weather.ru/pogoda/south_korea/',
  'Ямайка': 'http://world-weather.ru/pogoda/jamaica/',
  'Япония': 'http://world-weather.ru/pogoda/japan/'
};
