name: weathers
description: "Weather browser application by AdrianS4957Y."
publish_to: 'none'
version: 1.0.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  html: ^0.15.4
  http: ^1.2.2
  logging: ^1.0.2
  loading_animation_widget: ^1.2.1
  open_meteo: ^2.0.1
  intl: ^0.19.0
  flutter_svg: ^2.0.10+1
  rename_app: ^1.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
  - assets/rainy_big.png
  - assets/snowy_big.png
  - assets/windy_big.png
  - assets/search_icon.png
  - assets/states/wind.png
  - assets/states/humidity.png
  - assets/states/rainfall.png
  - assets/cities-dataset.json
  - assets/sky_states/
  - assets/states/
