name: weathers
description: "Weather application."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  html: ^0.15.4
  http: ^1.2.2
  loading_animation_widget: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
  - assets/rainy_big.png
  - assets/snowy_big.png
  - assets/windy_big.png
  - assets/search_icon.png
  - assets/states/wind.png
  - assets/states/humidity.png
  - assets/states/rainfall.png
